MOSIP-16638 : Ignore duplicate requests for same latest transaction i…
mosip/registration pull request #1140
Opened 2021-08-12 10:14 UTC by MonobikashDas

…d in bio-dedupe stage

2021-08-13 04:12 UTC, gsasikumar requested changes

2021-08-13 04:12 UTC, gsasikumar commented on registration-processor/registration-processor-info-storage-service/src/main/java/io/mosip/registration/processor/packet/storage/utils/ABISHandlerUtil.java
> +				if (!identifyReq.getStatusCode().equalsIgnoreCase(AbisStatusCode.PROCESSED.toString())) {
can u make this witout else

2021-08-13 04:12 UTC, gsasikumar commented on registration-processor/registration-processor-info-storage-service/src/main/java/io/mosip/registration/processor/packet/storage/utils/ABISHandlerUtil.java
> +				if (identifyReq.getStatusCode().equalsIgnoreCase(AbisStatusCode.PROCESSED.toString())) {
do we need this method? U r checking the same as the previous method. can we not reuse the older method

2021-08-16 07:53 UTC, MonobikashDas commented on registration-processor/registration-processor-info-storage-service/src/main/java/io/mosip/registration/processor/packet/storage/utils/ABISHandlerUtil.java
> +				if (!identifyReq.getStatusCode().equalsIgnoreCase(AbisStatusCode.PROCESSED.toString())) {
Fixed

2021-08-18 10:13 UTC, gsasikumar approved these changes

2021-08-18 10:14 UTC, merged