MOSIP-23025 : healthcheck and retry fix for activemq connection + routing config for securezone
mosip/registration pull request #1584
Opened 2022-08-05 13:28 UTC by MonobikashDas

2022-08-05 15:52 UTC, gsasikumar requested changes

2022-08-05 15:52 UTC, gsasikumar commented on registration-processor/registration-processor-core/src/main/java/io/mosip/registration/processor/core/abstractverticle/StageHealthCheckHandler.java
>  			promise.complete(Status.KO(result));
Is it KO or OK?

2022-08-05 15:52 UTC, gsasikumar commented on registration-processor/registration-processor-core/src/main/java/io/mosip/registration/processor/core/abstractverticle/StageHealthCheckHandler.java
> +		if (res == null || !msg.equalsIgnoreCase(res)) {
How can "res" become null? We are just initialising. Is it a typo? Are you trying to chk the msg?

2022-08-05 15:52 UTC, gsasikumar commented on registration-processor/registration-processor-core/src/main/java/io/mosip/registration/processor/core/abstractverticle/StageHealthCheckHandler.java
> +			promise.complete(Status.KO(result));
KO or OK?

2022-08-05 15:52 UTC, gsasikumar commented on registration-processor/registration-processor-core/src/main/java/io/mosip/registration/processor/core/queue/impl/MosipActiveMqImpl.java
> +                        "", "Could not obtain queue connection. System will retry for 10 times. retrycount = "
Retry count is set to 1 above? Retry count should be configurable

2022-08-05 15:52 UTC, gsasikumar commented on registration-processor/registration-processor-core/src/main/java/io/mosip/registration/processor/core/queue/impl/MosipActiveMqImpl.java
> +                        "", "Could not obtain queue connection. System will retry for 10 times. retrycount = "
Also make it default as 10

2022-08-05 15:52 UTC, gsasikumar commented on registration-processor/registration-processor-core/src/main/java/io/mosip/registration/processor/core/queue/impl/MosipActiveMqImpl.java
> +                        "", "Could not obtain queue connection. System will retry for 10 times. retrycount = "
In the logs don't hard code to 10

2022-08-08 11:10 UTC, MonobikashDas commented on registration-processor/registration-processor-core/src/main/java/io/mosip/registration/processor/core/abstractverticle/StageHealthCheckHandler.java
>  			promise.complete(Status.KO(result));
Vertx provides health check status as OK and KO. In case of success status OK is used and failure KO is used.

2022-08-08 11:10 UTC, MonobikashDas commented on registration-processor/registration-processor-core/src/main/java/io/mosip/registration/processor/core/abstractverticle/StageHealthCheckHandler.java
> +		if (res == null || !msg.equalsIgnoreCase(res)) {
We receive "res" from activemq and we have initialized msg string. 
So we are checking if res is null or res doesnot match the actual message we sent to queue then health check is failed.

2022-08-08 11:10 UTC, MonobikashDas commented on registration-processor/registration-processor-core/src/main/java/io/mosip/registration/processor/core/abstractverticle/StageHealthCheckHandler.java
> +			promise.complete(Status.KO(result));
KO

2022-08-08 11:10 UTC, MonobikashDas commented on registration-processor/registration-processor-core/src/main/java/io/mosip/registration/processor/core/queue/impl/MosipActiveMqImpl.java
> +                        "", "Could not obtain queue connection. System will retry for 10 times. retrycount = "
Done.

2022-08-09 09:38 UTC, gsasikumar approved these changes

2022-08-09 09:38 UTC, merged