MOSIP-21238 relocate method call
mosip/registration pull request #1594
Opened 2022-08-19 08:07 UTC by Shubhamjwl

2022-08-23 05:27 UTC, MonobikashDas requested changes
This will not work. Refer commits for this jira id = https://mosip.atlassian.net/browse/MOSIP-22192
cherry pick commits.

2022-08-30 09:00 UTC, Shubhamjwl commented
I  recreated that scenario with @Chandra  and checked issue into the logs, showing invalid reg id exception, that why i made changes after the discussion from @Shilpa, because she was already made the same changes and suggested me.

2022-09-22 08:44 UTC, sowmya695 approved these changes

2022-09-22 09:04 UTC, MonobikashDas approved these changes

2022-09-22 09:04 UTC, merged