Added credential requestor documentation
mosip/registration pull request #1609
Opened 2022-09-20 16:16 UTC by MonobikashDas

2024-02-01 09:30 UTC, sowmya695 approved these changes

2024-02-01 14:20 UTC, vishwa-vyom requested changes

2024-02-01 14:20 UTC, vishwa-vyom commented on registration-processor/post-processor/registration-processor-credential-requestor-stage/README.md
> +In the current system, the print stage's role extends beyond traditional printing activities. Its primary function now revolves around initiating a request for credential generation once a Unique Ide
" This request is not aimed at physical printing but serves as a mechanism to gather additional information for specific partners" - this line need to be little reworded, since it can be still used for physical printing, also calling gather additional information for partners sounds privicy concerning.

2024-03-05 06:14 UTC, sowmya695 commented
Closing this PR ,this documentation we will take care in develop branch
cc @vadherhemant @vishwa-vyom

2024-03-05 06:14 UTC, closed without merging