MOSIP-26716 Code changes
mosip/registration pull request #1679
Opened 2023-03-30 12:46 UTC by sowmya695

2023-03-30 12:54 UTC, sowmya695 commented on registration-processor/registration-processor-core/src/main/java/io/mosip/registration/processor/core/tracing/VertxWrapperHandler.java
> +		ContextualData.put(TracingConstant.RID_KEY, getRid(obj, context));
This change I have added because it will throw null pointer exception ,it will not proceed to api.Same change I copied from develop branch

2023-04-03 10:01 UTC, vishwa-vyom requested changes

2023-04-03 10:01 UTC, vishwa-vyom commented on registration-processor/post-processor/registration-processor-message-sender-stage/src/main/java/io/mosip/registration/processor/message/sender/stage/MessageSenderApi.java
> +			if (registrationStatusDto != null) {
Lets also check if the reg type matches

2023-04-03 10:01 UTC, vishwa-vyom commented on registration-processor/post-processor/registration-processor-message-sender-stage/src/main/java/io/mosip/registration/processor/message/sender/stage/MessageSenderApi.java
> +			} else {
You can optionally move this else condition to first with a inverted condition check  to avoid nexted code

2023-04-03 10:01 UTC, vishwa-vyom commented on registration-processor/post-processor/registration-processor-message-sender-stage/src/main/java/io/mosip/registration/processor/message/sender/stage/MessageSenderApi.java
> +				messageDTO.setReg_type(RegistrationType.valueOf(messageSenderRequestDTO.getReg_type()));
Lets fill the other fields also to be consistent with other stage message with default values ?

2023-04-03 10:01 UTC, vishwa-vyom commented on registration-processor/post-processor/registration-processor-message-sender-stage/src/main/java/io/mosip/registration/processor/message/sender/stage/MessageSenderApi.java
> +	 *
why empty comment ?

2023-04-03 10:01 UTC, vishwa-vyom commented on registration-processor/post-processor/registration-processor-message-sender-stage/src/main/java/io/mosip/registration/processor/message/sender/validator/MessageSenderRequestValidator.java
> +
can we validate both rid and regtype is not null or not empty ?

2023-04-03 10:01 UTC, vishwa-vyom commented on registration-processor/registration-processor-core/src/main/java/io/mosip/registration/processor/core/message/sender/dto/MessageSenderRequestDTO.java
> +	private String reg_type;
Can we keep this as camel case ?

2023-04-03 10:59 UTC, sowmya695 commented on registration-processor/post-processor/registration-processor-message-sender-stage/src/main/java/io/mosip/registration/processor/message/sender/stage/MessageSenderApi.java
> +			if (registrationStatusDto != null) {
fixed

2023-04-03 10:59 UTC, sowmya695 commented on registration-processor/post-processor/registration-processor-message-sender-stage/src/main/java/io/mosip/registration/processor/message/sender/stage/MessageSenderApi.java
> +			} else {
fixed

2023-04-03 10:59 UTC, sowmya695 commented on registration-processor/post-processor/registration-processor-message-sender-stage/src/main/java/io/mosip/registration/processor/message/sender/stage/MessageSenderApi.java
> +				messageDTO.setReg_type(RegistrationType.valueOf(messageSenderRequestDTO.getReg_type()));
fixed

2023-04-03 10:59 UTC, sowmya695 commented on registration-processor/post-processor/registration-processor-message-sender-stage/src/main/java/io/mosip/registration/processor/message/sender/stage/MessageSenderApi.java
> +	 *
removed

2023-04-03 10:59 UTC, sowmya695 commented on registration-processor/post-processor/registration-processor-message-sender-stage/src/main/java/io/mosip/registration/processor/message/sender/validator/MessageSenderRequestValidator.java
> +
fixed

2023-04-03 10:59 UTC, sowmya695 commented on registration-processor/registration-processor-core/src/main/java/io/mosip/registration/processor/core/message/sender/dto/MessageSenderRequestDTO.java
> +	private String reg_type;
fixed

2023-04-03 11:39 UTC, vishwa-vyom commented on registration-processor/post-processor/registration-processor-message-sender-stage/src/main/java/io/mosip/registration/processor/message/sender/stage/MessageSenderApi.java
> +			} else {
Can we avoid the else in the first if since we are throwning exception ? Also we can do the same for the next if condition of regtype equals, by inversing and avoid the next else

2023-04-03 11:53 UTC, sowmya695 commented on registration-processor/post-processor/registration-processor-message-sender-stage/src/main/java/io/mosip/registration/processor/message/sender/stage/MessageSenderApi.java
> +			} else {
fixed

2023-04-04 06:42 UTC, vishwa-vyom approved these changes

2023-04-04 06:45 UTC, merged