Mosip 23833
mosip/registration pull request #1694
Opened 2023-05-08 06:55 UTC by ckm007

2023-05-11 07:52 UTC, sowmya695 commented on db_upgrade_scripts/mosip_regprc/sql/1.1.5.5_to_1.2.0.1-B1_rollback.sql
> +ALTER TABLE regprc.registration DROP COLUMN IF EXISTS default_resume_action;
@ckm007  As part of release-1.2.0.1 many other changes for same table and other tables in regproc, Why it is added only for these two columns here

2023-05-11 08:05 UTC, sowmya695 requested changes
Please check the one of clarification needed

2023-05-12 13:10 UTC, sowmya695 requested changes
Please fix the comments

2023-05-12 13:10 UTC, sowmya695 commented on db_upgrade_scripts/mosip_regprc/upgrade.properties
> +TARGET_VERSION=
Please update it as UPGRADE_VERSION

2023-05-12 13:10 UTC, sowmya695 commented on db_upgrade_scripts/mosip_regprc/upgrade.properties
> +ACTION=
Please move this to first line as it was not working at the end

2023-05-12 13:10 UTC, sowmya695 commented on db_upgrade_scripts/mosip_regprc/upgrade.sh
> +if [ "$ACTION" == "upgrade" ]; then
Please replace "$ACTION" with $ACTION

2023-05-12 13:10 UTC, sowmya695 requested changes
Please fix the comments

2023-05-12 13:10 UTC, sowmya695 requested changes
Please fix the comments

2023-05-15 09:57 UTC, vishwa-vyom approved these changes
The open comments will be taken care by Sowmya in the new PR, so this PR is approved

2023-05-15 09:58 UTC, sowmya695 approved these changes
I will do the necessary changes

2023-05-15 09:59 UTC, merged