MOSIP-32461 Changing commons  versions for 1.3.x branch
mosip/registration pull request #1923
Opened 2024-10-07 08:35 UTC by Khuddusshariff0022

2024-10-08 11:17 UTC, ashok-ksharma requested changes

2024-10-08 11:17 UTC, ashok-ksharma commented on registration-processor/pom.xml
>  		<kernel.templatemanager.velocity.version>1.3.0-SNAPSHOT</kernel.templatemanager.velocity.version>
We should change <kernel.templatemanager.velocity.version> this to 1.3.0-beta.1

2024-10-08 11:17 UTC, ashok-ksharma commented on registration-processor/pom.xml
>  		<sonar.coverage.exclusions>**/dto/**,
1. Do we need this bom dependency here or we can change the bom version with property: https://github.com/mosip/registration/blob/release-1.3.x/registration-processor/core-processor/registration-processor-verification-stage/pom.xml#L33
2. Do we need to define this or we can directly refer from parent pom : https://github.com/mosip/registration/blob/release-1.3.x/registration-processor/registration-processor-notification-service/pom.xml#L19

2024-10-09 05:25 UTC, Khuddusshariff0022 commented on registration-processor/pom.xml
>  		<kernel.templatemanager.velocity.version>1.3.0-SNAPSHOT</kernel.templatemanager.velocity.version>
done.

2024-10-09 06:20 UTC, Khuddusshariff0022 commented on registration-processor/pom.xml
>  		<sonar.coverage.exclusions>**/dto/**,
1. For bom dependency made it to refer property for version.

2. shifted the property to parent pom.

2024-10-15 13:30 UTC, ashok-ksharma approved these changes

2024-10-17 09:23 UTC, ckm007 approved these changes

2024-10-17 10:10 UTC, merged