[MOSIP_32756] adding Readme changes.
mosip/registration pull request #1932
Opened 2024-11-08 12:15 UTC by Khuddusshariff0022

2024-11-08 14:26 UTC, ashok-ksharma requested changes

2024-11-08 14:26 UTC, ashok-ksharma commented on README.md
>  ## Test
**Registration processor in sandbox** link is not correct.

2024-11-08 14:26 UTC, ashok-ksharma commented on README.md
> +Automated functional tests available in [DSL Automation](https://docs.mosip.io/1.2.0/test-automation/dsl-test-rig-automation)
The link is wrong. It is about the documentation not about the actual test scripts. Please change the same.

2024-11-08 14:26 UTC, ashok-ksharma commented on README.md
>  API documentation is available [here](https://docs.mosip.io/1.2.0/api)
API documentation link is not working.

2024-11-09 13:35 UTC, Khuddusshariff0022 commented on README.md
> +Automated functional tests available in [DSL Automation](https://docs.mosip.io/1.2.0/test-automation/dsl-test-rig-automation)
Done.

2024-11-09 13:39 UTC, Khuddusshariff0022 commented on README.md
>  API documentation is available [here](https://docs.mosip.io/1.2.0/api)
added this link.  https://[mosip.github.io/documentation/1.2.0/1.2.0.html](https://mosip.github.io/documentation/1.2.0/1.2.0.html)

2024-11-11 06:28 UTC, ashok-ksharma approved these changes

2024-11-11 11:08 UTC, merged