Fixed Constraint violation exception for global param (Col : TYP)
mosip/registration pull request #675
Opened 2021-01-29 06:47 UTC by yaswanths2

2021-02-04 16:48 UTC, gsasikumar approved these changes

2021-02-06 05:34 UTC, yaswanths2 commented
Resolved Conflicts

2021-02-08 12:19 UTC, gsasikumar requested changes

2021-02-08 12:19 UTC, gsasikumar commented on registration/registration-services/src/main/java/io/mosip/registration/service/config/impl/GlobalParamServiceImpl.java
> +						if (responseMap.containsKey("configDetail") && responseMap.get("configDetail") != null) {
why not use this ? responseMap.getOrDefault

2021-02-15 10:39 UTC, merged